### ISSUE TITLE
Using Stack Trace to get caller method's name isn't good.

### ISSUE THREAD

**Issue by IgorSzymanski** [DavidDuwaer/Coloquent#33]
https://github.com/DavidDuwaer/Coloquent/blob/e635ba8ea80be561c2da0578aba1e08aa74edba6/lib/util/Reflection.ts#L3-L11

This method is problematic for a few reasons:
Using stack trace is pretty slow and the output may vary for different browsers. And it feels a bit hacky. In my case the regex fails, because the output for me consists of slashes

> at Film.webpackJsonp../models/Film.ts.Film.author (

https://github.com/DavidDuwaer/Coloquent/blob/e635ba8ea80be561c2da0578aba1e08aa74edba6/lib/util/Reflection.ts#L5
 would have to be
```js
let re = /@|at [a-zA-Z0-9\.\/_]+\.([a-zA-Z0-9_]+) \(/g; 
```
or even

```js
let re = /@|at [^ ]+\.([a-zA-Z0-9_]+) \(/g; 
```

My suggestion would break backward compatibility, but I would just let define the relation name in `Model.hasMany()` abd `Model.hasOne()` like this:

```ts
    protected hasMany(relatedType: typeof Model, relationName: string): ToManyRelation
    {
        return new ToManyRelation(relatedType, this, relationName);
    }

    protected hasOne(relatedType: typeof Model, relationName: string): ToOneRelation
    {
        return new ToOneRelation(relatedType, this, relationName);
    }
```

It's faster, less faulty, not so much tedious and actually lets the user remap relation name if for some reason they don't like the name backend API serves them.

What do you think?

**Comment by DavidDuwaer** [comment]
I agree, using stack trace for this is a hack. Indeed, the problem is twofold: it is probably slow, and it is (as far as I know) not standardized. At least for now, to not break backward compatibility, we'll allow one to bypass, but we'll still support it. I've overloaded the `Model.hasMany` and `Model.hasOne` with the method signature that you suggested so you have the option to manually override those relation names. I've also expanded that regex so it matches your scenario in case you're using the stacktrace (I've chosen your more conservative regex suggestion).
